### ISSUE TITLE
Error loading HDBSCAN

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1028]
Minimal test notebook:
```
%pyspark
import hdbscan
```

Error message:
```
Traceback (most recent call last):
  File "/tmp/1664452959634-0/zeppelin_python.py", line 158, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib64/python3.7/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/usr/local/lib64/python3.7/site-packages/hdbscan/hdbscan_.py", line 334, in <module>
    algorithm='best', memory=Memory(cachedir=None, verbose=0),
TypeError: __init__() got an unexpected keyword argument 'cachedir'
```

* Deployment: `iris-gaia-blue-20220923`
* GitHub branch: [20220919-zrq-gardening](https://github.com/Zarquan/gaia-dmp/tree/20220919-zrq-gardening)

**Comment by Zarquan** [comment]
Fixed by PR #1041
